# This file is used to configure your project.
# Read more about the various options under:
# https://setuptools.pypa.io/en/latest/userguide/declarative_config.html
# https://setuptools.pypa.io/en/latest/references/keywords.html

[metadata]
name = recon2024
description = "2022 update of R/ECON model"
author = Joao Rodrigues
author_email = joao.f.d.rodrigues@protonmail.com
license = None
license_files = none
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8; variant=GFM
url = https://github.com/RECON2024/recon2024

# Add here related links, for example:
# project_urls =
#     Documentation = http://...?

# Change if running only on Windows, Mac or Linux (comma-separated)
platforms = any

# Add here all kinds of additional classifiers as defined under
# https://pypi.org/classifiers/
classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python


[options]
zip_safe = False
packages = find_namespace:
include_package_data = True
package_dir =
    =src

# Require a min/specific Python version (comma-separated conditions)
# python_requires = >=3.8

# Add here dependencies of your project (line-separated), e.g. requests>=2.2,<3.0.
# Version specifiers like >=2.2,<3.0 avoid problems due to API changes in
# new major versions. This works if the required packages follow Semantic Versioning.
# For more information, check out https://semver.org/.
# pandas>=1.5.3
install_requires =
  importlib-metadata
  asttokens>=2.4.1
  cloudpickle>=3.0.0
  comm>=0.2.2
  debugpy>=1.8.2
  decorator>=5.1.1
  et-xmlfile>=1.1.0
  exceptiongroup>=1.2.1
  executing>=2.0.1
  importlib_metadata>=8.0.0
  ipykernel>=6.29.5
  ipython>=8.26.0
  jedi>=0.19.1
  jupyter_client>=8.6.2
  jupyter_core>=5.7.2
  matplotlib-inline>=0.1.7
  nest-asyncio>=1.6.0
  numpy>=2.0.0
  openpyxl>=3.1.5
  packaging>=24.1
  pandas>=2.2.2
  parso>=0.8.4
  pexpect>=4.9.0
  platformdirs>=4.2.2
  prompt_toolkit>=3.0.47
  psutil>=6.0.0
  ptyprocess>=0.7.0
  pure-eval>=0.2.2
  Pygments>=2.18.0
  python-dateutil>=2.9.0.post0
  pytz>=2024.1
  PyYAML>=6.0.1
  pyzmq>=26.0.3
  six>=1.16.0
  spyder-kernels>=2.5.2
  stack-data>=0.6.3
  tornado>=6.4.1
  traitlets>=5.14.3
  typing_extensions>=4.12.2
  tzdata>=2024.1
  wcwidth>=0.2.13
  wurlitzer>=3.1.1
  zipp>=3.19.2
  scipy>=1.14.1
  spyder-kernels>=2.5.2
  xlsxwriter>=3.2.0
  line_profiler>=4.1.3
  beautifulsoup4>=4.12.3
  xmltodict>=0.14.2
  requests>=2.32.4
  xlrd>=2.0.2
  statsmodels>=0.14.5

[options.packages.find]
where = src
exclude =
    tests


[options.extras_require]
# Add here additional requirements for extra features, to install with:
# `pip install utilities[PDF]` like:
# PDF = ReportLab; RXP

# Add here test requirements (semicolon/line-separated)
#    pandas>=1.5.3
testing =
    setuptools>=65.6.3
    pytest>=7.2.2
    pytest-cov>=4.0.0
    importlib_resources

[options.entry_points]
# Add here console scripts like:
console_scripts =
  recon2024 = recon2024.main:main
  recon2024_combine_regions = recon2024.combine_regions:main

[tool:pytest]
# Specify command line options as you would do when invoking pytest directly.
# e.g. --cov-report html (or xml) for html/xml output or --junitxml junit.xml
# in order to write a coverage file that can be read by Jenkins.
# CAUTION: --cov flags may prohibit setting breakpoints while debugging.
#          Comment those flags to avoid this pytest issue.
addopts =
#    --cov utilities --cov-report term-missing
    --verbose
    --log-cli-level=INFO
norecursedirs =
    dist
    build
    .tox
testpaths = tests
# Use pytest markers to select/deselect specific tests
# markers =
#     slow: mark tests as slow (deselect with '-m "not slow"')
#     system: mark end-to-end system tests

[devpi:upload]
# Options for the devpi: PyPI server and packaging tool
# VCS export must be deactivated since we are using setuptools-scm
no_vcs = 1
formats = bdist_wheel

[flake8]
# Some sane defaults for the code style checker flake8
max_line_length = 88
extend_ignore = E203, W503
# ^  Black-compatible
#    E203 and W503 have edge cases handled by black
exclude =
    .tox
    build
    dist
    .eggs
    docs/conf.py


